//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace POCControlCenter {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WinFormsStringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormsStringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POCControlCenter.WinFormsStringResource", typeof(WinFormsStringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 名称不允许为空 的本地化字符串。
        /// </summary>
        public static string CreateTmpGrpNameISNull {
            get {
                return ResourceManager.GetString("CreateTmpGrpNameISNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间跨度不能超过7天 的本地化字符串。
        /// </summary>
        public static string DateSpanMustLess7days {
            get {
                return ResourceManager.GetString("DateSpanMustLess7days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除组失败 的本地化字符串。
        /// </summary>
        public static string DelTmpGroupFail {
            get {
                return ResourceManager.GetString("DelTmpGroupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备异常, 你无法对讲和语音通话! 的本地化字符串。
        /// </summary>
        public static string DeviceError_AudioInput {
            get {
                return ResourceManager.GetString("DeviceError_AudioInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备异常, 对方说的话你听不到! 的本地化字符串。
        /// </summary>
        public static string DeviceError_AudioOutput {
            get {
                return ResourceManager.GetString("DeviceError_AudioOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备异常, 会影响视频通话，对方看不到你的画面! 的本地化字符串。
        /// </summary>
        public static string DeviceError_VideoInput {
            get {
                return ResourceManager.GetString("DeviceError_VideoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备正常 的本地化字符串。
        /// </summary>
        public static string DeviceNormal {
            get {
                return ResourceManager.GetString("DeviceNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入组名称 的本地化字符串。
        /// </summary>
        public static string EnterGrpName {
            get {
                return ResourceManager.GetString("EnterGrpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入值 的本地化字符串。
        /// </summary>
        public static string EnterValuePrompt {
            get {
                return ResourceManager.GetString("EnterValuePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出异常 的本地化字符串。
        /// </summary>
        public static string ExcelExportFail {
            get {
                return ResourceManager.GetString("ExcelExportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出成功 的本地化字符串。
        /// </summary>
        public static string ExcelExportSuccess {
            get {
                return ResourceManager.GetString("ExcelExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定不用通知吗? 的本地化字符串。
        /// </summary>
        public static string FenceAlarmNoNotifyConfirm {
            get {
                return ResourceManager.GetString("FenceAlarmNoNotifyConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进入警告 的本地化字符串。
        /// </summary>
        public static string FenceAlarmTypeINCOME {
            get {
                return ResourceManager.GetString("FenceAlarmTypeINCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出去警告 的本地化字符串。
        /// </summary>
        public static string FenceAlarmTypeOUTCOME {
            get {
                return ResourceManager.GetString("FenceAlarmTypeOUTCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该围栏规则已经存在了，不允许重复增加 的本地化字符串。
        /// </summary>
        public static string FenceRuleAlreadyExist {
            get {
                return ResourceManager.GetString("FenceRuleAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择围栏的名单类型(白名单或黑名单) 的本地化字符串。
        /// </summary>
        public static string FenceRuleBlkWht {
            get {
                return ResourceManager.GetString("FenceRuleBlkWht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除吗？ 的本地化字符串。
        /// </summary>
        public static string FenceRuleDel {
            get {
                return ResourceManager.GetString("FenceRuleDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择人员 的本地化字符串。
        /// </summary>
        public static string FenceRulePerson {
            get {
                return ResourceManager.GetString("FenceRulePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择围栏告警类型(进入或出去) 的本地化字符串。
        /// </summary>
        public static string FenceRuleType {
            get {
                return ResourceManager.GetString("FenceRuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁止从固定组中强拆某成员(只有web管理员有权限) 的本地化字符串。
        /// </summary>
        public static string FocreRemoveFrmFixGroupError {
            get {
                return ResourceManager.GetString("FocreRemoveFrmFixGroupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超始时间不能大于终止时间 的本地化字符串。
        /// </summary>
        public static string FromDateMustBeforeToDate {
            get {
                return ResourceManager.GetString("FromDateMustBeforeToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐号状态 的本地化字符串。
        /// </summary>
        public static string LifeState {
            get {
                return ResourceManager.GetString("LifeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遥晕 的本地化字符串。
        /// </summary>
        public static string LifeState_0 {
            get {
                return ResourceManager.GetString("LifeState_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        public static string LifeState_1 {
            get {
                return ResourceManager.GetString("LifeState_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遥毙 的本地化字符串。
        /// </summary>
        public static string LifeState_NE1 {
            get {
                return ResourceManager.GetString("LifeState_NE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 baidu_fence_location_new_ex_requirejs.jsp 的本地化字符串。
        /// </summary>
        public static string LocationBaiduMAP {
            get {
                return ResourceManager.GetString("LocationBaiduMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 baidu_fence_alarm_notify.jsp 的本地化字符串。
        /// </summary>
        public static string LocationFenceAlarmMap {
            get {
                return ResourceManager.GetString("LocationFenceAlarmMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 baidu_fence.jsp 的本地化字符串。
        /// </summary>
        public static string LocationFenceMAP {
            get {
                return ResourceManager.GetString("LocationFenceMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 baidu_trackback.jsp 的本地化字符串。
        /// </summary>
        public static string LocationTrackMAP {
            get {
                return ResourceManager.GetString("LocationTrackMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号不能为空！ 的本地化字符串。
        /// </summary>
        public static string Login_ErrorText1 {
            get {
                return ResourceManager.GetString("Login_ErrorText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空！ 的本地化字符串。
        /// </summary>
        public static string Login_ErrorText2 {
            get {
                return ResourceManager.GetString("Login_ErrorText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号 或 密码 错误！ 的本地化字符串。
        /// </summary>
        public static string Login_ErrorText3 {
            get {
                return ResourceManager.GetString("Login_ErrorText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎登入多媒体指挥调度系统 的本地化字符串。
        /// </summary>
        public static string LoginWelcome {
            get {
                return ResourceManager.GetString("LoginWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击对讲 的本地化字符串。
        /// </summary>
        public static string Main_buttonTALK_Text1 {
            get {
                return ResourceManager.GetString("Main_buttonTALK_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止对讲 的本地化字符串。
        /// </summary>
        public static string Main_buttonTALK_Text2 {
            get {
                return ResourceManager.GetString("Main_buttonTALK_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Main_FileTrnText1 {
            get {
                return ResourceManager.GetString("Main_FileTrnText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Main_FileTrnText2 {
            get {
                return ResourceManager.GetString("Main_FileTrnText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Main_FileTrnText3 {
            get {
                return ResourceManager.GetString("Main_FileTrnText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Main_FileTrnText4 {
            get {
                return ResourceManager.GetString("Main_FileTrnText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Main_FileTrnText5 {
            get {
                return ResourceManager.GetString("Main_FileTrnText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录用户名 的本地化字符串。
        /// </summary>
        public static string Main_labelACCOUNT_sub1 {
            get {
                return ResourceManager.GetString("Main_labelACCOUNT_sub1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对讲组 的本地化字符串。
        /// </summary>
        public static string Main_labelACCOUNT_sub2 {
            get {
                return ResourceManager.GetString("Main_labelACCOUNT_sub2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在说话... 的本地化字符串。
        /// </summary>
        public static string Main_labelPlayerName_Text {
            get {
                return ResourceManager.GetString("Main_labelPlayerName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开链接 的本地化字符串。
        /// </summary>
        public static string Main_RTBRecord_s1 {
            get {
                return ResourceManager.GetString("Main_RTBRecord_s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统提示 的本地化字符串。
        /// </summary>
        public static string Main_RTBRecord_s2 {
            get {
                return ResourceManager.GetString("Main_RTBRecord_s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对讲中 的本地化字符串。
        /// </summary>
        public static string Main_timerPOCrobMIC_s1 {
            get {
                return ResourceManager.GetString("Main_timerPOCrobMIC_s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string Main_timerPOCrobMIC_s2 {
            get {
                return ResourceManager.GetString("Main_timerPOCrobMIC_s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有文件 的本地化字符串。
        /// </summary>
        public static string Main_trtSendFile_s1 {
            get {
                return ResourceManager.GetString("Main_trtSendFile_s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件 的本地化字符串。
        /// </summary>
        public static string Main_trtSendFile_s2 {
            get {
                return ResourceManager.GetString("Main_trtSendFile_s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        public static string Main_trtSendFile_s3 {
            get {
                return ResourceManager.GetString("Main_trtSendFile_s3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string Main_trtSendFile_s4 {
            get {
                return ResourceManager.GetString("Main_trtSendFile_s4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您已经取消了文件 的本地化字符串。
        /// </summary>
        public static string Main_trtSendFile_s5 {
            get {
                return ResourceManager.GetString("Main_trtSendFile_s5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 的传输 的本地化字符串。
        /// </summary>
        public static string Main_trtSendFile_s6 {
            get {
                return ResourceManager.GetString("Main_trtSendFile_s6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string Main_trtSendFile_s7 {
            get {
                return ResourceManager.GetString("Main_trtSendFile_s7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经传输完成 的本地化字符串。
        /// </summary>
        public static string Main_trtSendFile_s8 {
            get {
                return ResourceManager.GetString("Main_trtSendFile_s8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经传输完成,保存路径 的本地化字符串。
        /// </summary>
        public static string Main_trtSendFile_s9 {
            get {
                return ResourceManager.GetString("Main_trtSendFile_s9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像文件 的本地化字符串。
        /// </summary>
        public static string Main_trtSendPicture_s1 {
            get {
                return ResourceManager.GetString("Main_trtSendPicture_s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本不支持发送大于 10M 的图片，请使用发送文件功能来发送 的本地化字符串。
        /// </summary>
        public static string Main_trtSendPicture_s2 {
            get {
                return ResourceManager.GetString("Main_trtSendPicture_s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统提示 的本地化字符串。
        /// </summary>
        public static string Main_trtSendPicture_s3 {
            get {
                return ResourceManager.GetString("Main_trtSendPicture_s3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放结束 的本地化字符串。
        /// </summary>
        public static string MediaState_ended {
            get {
                return ResourceManager.GetString("MediaState_ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现异常 的本地化字符串。
        /// </summary>
        public static string MediaState_errored {
            get {
                return ResourceManager.GetString("MediaState_errored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开中 的本地化字符串。
        /// </summary>
        public static string MediaState_opened {
            get {
                return ResourceManager.GetString("MediaState_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放中 的本地化字符串。
        /// </summary>
        public static string MediaState_playing {
            get {
                return ResourceManager.GetString("MediaState_playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无数据 的本地化字符串。
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未有发现围栏定义 的本地化字符串。
        /// </summary>
        public static string NoFoundFenceDefine {
            get {
                return ResourceManager.GetString("NoFoundFenceDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件... 的本地化字符串。
        /// </summary>
        public static string p2pFilesSend_s1 {
            get {
                return ResourceManager.GetString("p2pFilesSend_s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传等待您接收文件... 的本地化字符串。
        /// </summary>
        public static string p2pFilesSend_s2 {
            get {
                return ResourceManager.GetString("p2pFilesSend_s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字节 的本地化字符串。
        /// </summary>
        public static string p2pFilesSend_s3 {
            get {
                return ResourceManager.GetString("p2pFilesSend_s3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知大小 的本地化字符串。
        /// </summary>
        public static string p2pFilesSend_s4 {
            get {
                return ResourceManager.GetString("p2pFilesSend_s4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要终止文件的传输吗？ 的本地化字符串。
        /// </summary>
        public static string p2pFilesSend_s5 {
            get {
                return ResourceManager.GetString("p2pFilesSend_s5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string p2pFilesSend_s6 {
            get {
                return ResourceManager.GetString("p2pFilesSend_s6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档 的本地化字符串。
        /// </summary>
        public static string p2pFilesSend_s7 {
            get {
                return ResourceManager.GetString("p2pFilesSend_s7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在发送文件... 的本地化字符串。
        /// </summary>
        public static string p2pFilesSend_s8 {
            get {
                return ResourceManager.GetString("p2pFilesSend_s8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在接收文件... 的本地化字符串。
        /// </summary>
        public static string p2pFilesSend_s9 {
            get {
                return ResourceManager.GetString("p2pFilesSend_s9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已是第一页了 的本地化字符串。
        /// </summary>
        public static string PageNoFirstAlert {
            get {
                return ResourceManager.GetString("PageNoFirstAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已是最后页了 的本地化字符串。
        /// </summary>
        public static string PageNoLastAlert {
            get {
                return ResourceManager.GetString("PageNoLastAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能导出，因为没有 Simsun字体 的本地化字符串。
        /// </summary>
        public static string PDFExportFail {
            get {
                return ResourceManager.GetString("PDFExportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF导出成功 的本地化字符串。
        /// </summary>
        public static string PDFExportSuccess {
            get {
                return ResourceManager.GetString("PDFExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到名字.. 的本地化字符串。
        /// </summary>
        public static string PersonCall_Text1 {
            get {
                return ResourceManager.GetString("PersonCall_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来电... 的本地化字符串。
        /// </summary>
        public static string PersonCall_Text2 {
            get {
                return ResourceManager.GetString("PersonCall_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在呼叫... 的本地化字符串。
        /// </summary>
        public static string PersonCall_Text3 {
            get {
                return ResourceManager.GetString("PersonCall_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 响铃 的本地化字符串。
        /// </summary>
        public static string PersonCall_Text4 {
            get {
                return ResourceManager.GetString("PersonCall_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string PersonCall_Text5 {
            get {
                return ResourceManager.GetString("PersonCall_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string PromptStr {
            get {
                return ResourceManager.GetString("PromptStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入页号无效 的本地化字符串。
        /// </summary>
        public static string QueryInValid_PageNo {
            get {
                return ResourceManager.GetString("QueryInValid_PageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页 的本地化字符串。
        /// </summary>
        public static string QueryPage {
            get {
                return ResourceManager.GetString("QueryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每页 的本地化字符串。
        /// </summary>
        public static string QueryPerPage {
            get {
                return ResourceManager.GetString("QueryPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条记录 的本地化字符串。
        /// </summary>
        public static string QueryRecDESC {
            get {
                return ResourceManager.GetString("QueryRecDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共 的本地化字符串。
        /// </summary>
        public static string QueryTotal {
            get {
                return ResourceManager.GetString("QueryTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定停止直播吗? 的本地化字符串。
        /// </summary>
        public static string QuestionStopLive {
            get {
                return ResourceManager.GetString("QuestionStopLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定停止监控吗? 的本地化字符串。
        /// </summary>
        public static string QuestionStopMoni {
            get {
                return ResourceManager.GetString("QuestionStopMoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存Excel文件 的本地化字符串。
        /// </summary>
        public static string SaveExcelFile {
            get {
                return ResourceManager.GetString("SaveExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择临时组 的本地化字符串。
        /// </summary>
        public static string SelectTmpGrp {
            get {
                return ResourceManager.GetString("SelectTmpGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择人员 的本地化字符串。
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线 的本地化字符串。
        /// </summary>
        public static string StatusOffline {
            get {
                return ResourceManager.GetString("StatusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线 的本地化字符串。
        /// </summary>
        public static string StatusOnline {
            get {
                return ResourceManager.GetString("StatusOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对讲单呼 的本地化字符串。
        /// </summary>
        public static string TalkP2P {
            get {
                return ResourceManager.GetString("TalkP2P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与 的本地化字符串。
        /// </summary>
        public static string TalkTo {
            get {
                return ResourceManager.GetString("TalkTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要删除临时组吗? 的本地化字符串。
        /// </summary>
        public static string TmpGroupDelConfirm {
            get {
                return ResourceManager.GetString("TmpGroupDelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改临时组名称 的本地化字符串。
        /// </summary>
        public static string TmpGrpNameModifyPrompt {
            get {
                return ResourceManager.GetString("TmpGrpNameModifyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直播 的本地化字符串。
        /// </summary>
        public static string Video_Live {
            get {
                return ResourceManager.GetString("Video_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控 的本地化字符串。
        /// </summary>
        public static string Video_Moni {
            get {
                return ResourceManager.GetString("Video_Moni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大化窗口 的本地化字符串。
        /// </summary>
        public static string VideoMaxWindow {
            get {
                return ResourceManager.GetString("VideoMaxWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (结束,时长: 的本地化字符串。
        /// </summary>
        public static string VideoMoniEndStrPrefix {
            get {
                return ResourceManager.GetString("VideoMoniEndStrPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒) 的本地化字符串。
        /// </summary>
        public static string VideoMoniEndStrSuffix {
            get {
                return ResourceManager.GetString("VideoMoniEndStrSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对方网络信号不好或者没有登入，请稍后再试 的本地化字符串。
        /// </summary>
        public static string VideoMonitorApplyFail {
            get {
                return ResourceManager.GetString("VideoMonitorApplyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还原窗口 的本地化字符串。
        /// </summary>
        public static string VideoRestoreWindow {
            get {
                return ResourceManager.GetString("VideoRestoreWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭声音 的本地化字符串。
        /// </summary>
        public static string VideoVoiceClose {
            get {
                return ResourceManager.GetString("VideoVoiceClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开声音 的本地化字符串。
        /// </summary>
        public static string VideoVoiceOpen {
            get {
                return ResourceManager.GetString("VideoVoiceOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对讲语音记录 的本地化字符串。
        /// </summary>
        public static string VoiceRecord {
            get {
                return ResourceManager.GetString("VoiceRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string VoiceRecord_CLOSE {
            get {
                return ResourceManager.GetString("VoiceRecord_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        public static string VoiceRecord_OPEN {
            get {
                return ResourceManager.GetString("VoiceRecord_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对讲话权 的本地化字符串。
        /// </summary>
        public static string VoiceRight {
            get {
                return ResourceManager.GetString("VoiceRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通话权 的本地化字符串。
        /// </summary>
        public static string VoiceRight_0 {
            get {
                return ResourceManager.GetString("VoiceRight_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先话权 的本地化字符串。
        /// </summary>
        public static string VoiceRight_1 {
            get {
                return ResourceManager.GetString("VoiceRight_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最高话权 的本地化字符串。
        /// </summary>
        public static string VoiceRight_2 {
            get {
                return ResourceManager.GetString("VoiceRight_2", resourceCulture);
            }
        }
    }
}
